#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

#FONT="InconsolataLGC Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
FONT="SF Pro"
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# topmost=on at end to replace current bar
bar=(
  height=30
  color=$BAR_COLOR
  # color="0xbf2e3440"
  #color=$BACKGROUND_1
  blur_radius=30
  border_width=0
  border_color=$BAR_BORDER_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=0
  padding_left=0
  y_offset=5
  margin=10
  topmost=window
  corner_radius=9 # was 5
)
sketchybar --bar "${bar[@]}"


defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:12.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:11.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=30
  background.corner_radius=9 # was 9
  background.border_width=0
  popup.background.border_width=1
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
# for i in "${!SPACE_ICONS[@]}"
# do
#  sid="$(($i+1))"
#  space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=7
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done

# Left
source "$ITEM_DIR/apple.sh"
# source "$ITEM_DIR/svim.sh"
source "$ITEM_DIR/spaces.sh"


# Center
# source "$ITEM_DIR/spotify.sh"
# source "$ITEM_DIR/media.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/calendar.sh"
# source "$ITEM_DIR/weather.sh"
# source "$ITEM_DIR/brew.sh"
# source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/input.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --hotload on

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
